# Group8: Preprocessing to devide data
### Zhu Shien & Mo Xiaoyun
We devided the data twice, use 20% and 10% of whole dataset respectively<br>
First time: 18740 images -> 12000 train, 1740 small scale test, 5000 inference<br>
Second time: 9400 images -> 6000 train, 900 small scale test, 2500 inference<br>
This notebook shows the process of the second time:<br>
* set data path
* get 10% images and corresponding XMLs
* devide images and XMLs into train,small scale test and large scale inference
* shuffle the data within each category

### Set the data path and verify that the file names are in sequence

In [1]:
# import the libiaries
import random as rm
import os
from shutil import copyfile, rmtree
import torch

In [2]:
# Set the data path
raw_dir ="D:\download\DACcontest\data_training_V4\data_training\\"
train_data_dir = "D:\download\DACcontest\data_training_V4"+"\\train_data\\"
train_label_dir = "D:\download\DACcontest\data_training_V4" + "\\train_label\\"
test_data_dir = "D:\download\DACcontest\data_training_V4" + "\\test_data\\"
test_label_dir = "D:\download\DACcontest\data_training_V4" + "\\test_label\\"
data_dir="D:\download\DACcontest" + "\\data\\"
label_dir="D:\download\DACcontest" + "\\label\\"
print(train_data_dir,train_label_dir)
print(test_data_dir,test_label_dir)
print(data_dir,label_dir)

D:\download\DACcontest\data_training_V4\train_data\ D:\download\DACcontest\data_training_V4\train_label\
D:\download\DACcontest\data_training_V4\test_data\ D:\download\DACcontest\data_training_V4\test_label\
D:\download\DACcontest\data\ D:\download\DACcontest\label\


In [3]:
# confirm that the images are in sequence
raw_list=os.listdir(raw_dir)
print(raw_list[0])
local_dir=raw_dir + raw_list[0] + "/"
print(local_dir)
num=0
for filename in os.listdir(local_dir):
    print(filename)
    num=num+1
    if num==20 :
        break

boat1
D:\download\DACcontest\data_training_V4\data_training\boat1/
000001.jpg
000001.xml
000002.jpg
000002.xml
000003.jpg
000003.xml
000004.jpg
000004.xml
000005.jpg
000005.xml
000006.jpg
000006.xml
000007.jpg
000007.xml
000008.jpg
000008.xml
000009.jpg
000009.xml
000010.jpg
000010.xml


### Get 10% of the whole dataset
Get 10% of the total images and save them in "data"<br>
Get corresponding xmls and save them in "label"<br>
Note that the .jpg and .xml are in the same folder

In [4]:
# set the ratio(counter) to get the images
# ratio=10 means that select the 1st image in every 10 images,
# so it's 10% of the total daset
ratio=10
accratio=2*ratio

global_num=0    # for all images
for cls in os.listdir(raw_dir):
    local_num=0 # for images in a floder
    local_dir=raw_dir + cls
    print(local_dir)
    print(global_num)
    # since we have to get the XMLs out as well,
    # so we use "justnow" to know wether to copy the XML
    justnow=0
    for filename in os.listdir(local_dir):
        if (local_num%accratio==0):
            copyfile(local_dir +'\\'+ filename, data_dir + cls + '_' + filename)
            justnow=1
            global_num+=1
        elif justnow==1 :
            copyfile(local_dir + '\\' +filename, label_dir + cls + '_' + filename)
            justnow=0
            global_num+=1
        local_num=local_num+1
        
print(global_num)
        

D:\download\DACcontest\data_training_V4\data_training\boat1
0
D:\download\DACcontest\data_training_V4\data_training\boat2
118
D:\download\DACcontest\data_training_V4\data_training\boat3
218
D:\download\DACcontest\data_training_V4\data_training\boat4
336
D:\download\DACcontest\data_training_V4\data_training\boat5
428
D:\download\DACcontest\data_training_V4\data_training\boat6
696
D:\download\DACcontest\data_training_V4\data_training\boat7
800
D:\download\DACcontest\data_training_V4\data_training\boat8
964
D:\download\DACcontest\data_training_V4\data_training\building1
1050
D:\download\DACcontest\data_training_V4\data_training\building2
1158
D:\download\DACcontest\data_training_V4\data_training\building3
1258
D:\download\DACcontest\data_training_V4\data_training\car1
1322
D:\download\DACcontest\data_training_V4\data_training\car10
1406
D:\download\DACcontest\data_training_V4\data_training\car11
1720
D:\download\DACcontest\data_training_V4\data_training\car12
2144
D:\download\DACcontest\d

## Set random numbers and devide the data into three parts
Use a vector to record the category of each image<br>
0 stands for train, 1 stands for small scale test, 2 stands for inference

In [5]:
# configurations
import time
rm.seed(time.time())
small_num=893
test_num=2500
train_num=6000
total_num=9393
rand=torch.zeros(total_num,dtype=torch.int8)

# set the rand[] for small scale test
i=0
while i<small_num :
    rm_num=rm.randint(0,total_num-1)
    if rand[rm_num]==0 :
        rand[rm_num]=1
        i=i+1
    else :
        continue

# set the rand[] for large scale inference
i=0
while i<test_num :
    rm_num=rm.randint(0,total_num-1)
    if rand[rm_num]==0 :
        rand[rm_num]=2
        i=i+1
    else :
        continue

In [6]:
# show the random numbers
print(rand[0:20])

tensor([0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0],
       dtype=torch.int8)


Devide data into three parts

In [8]:
# copy the images in the "data" folder 
global_num=0    # for all images
for filename in os.listdir(data_dir):
        if (rand[global_num]==1):
            copyfile(data_dir + filename, small_data_dir + filename)
        elif(rand[global_num]==2):
            copyfile(data_dir + filename, test_data_dir + filename)
        else :
            copyfile(data_dir + filename, train_data_dir + filename)
        global_num+=1    
print(global_num)

# copy the xmls in the "label" folder
global_num=0    # for all xmls
for filename in os.listdir(label_dir):
        if (rand[global_num]==1):
            copyfile(label_dir + filename, small_label_dir + filename)
        elif(rand[global_num]==2):
            copyfile(label_dir + filename, test_label_dir + filename)
        else :
            copyfile(label_dir + filename, train_label_dir + filename)
        global_num+=1    
print(global_num)

9393
9393


## Shuffle the images in the same folder
The data has been copy to the same folder of this notebook<br>
The folders:<br>
Group8-devide-data.ipynb<br>
--train_data<br>
--train_label<br>
--small_data<br>
--small_label<br>
--test_data<br>
--test_label<br>

Get a vector to record the shuffled position of train set,<br>
and shuffle the data and labels at the same time

In [9]:
# for train sets
import numpy as np
train=np.arange(6000)
print(train[0:10])
np.random.shuffle(train)
print(train[0:10])

[0 1 2 3 4 5 6 7 8 9]
[ 662 3238 3115 4232 5454 2488 5702 4728  415 1325]


In [10]:
# shuffle both .jpg & .XML of the train set

local_dir=os.getcwd()+"\\train_data\\"
print(local_dir)

i=0
for filename in os.listdir(local_dir):
    newname="mytrain"+str(train[i])+".jpg"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

i=0
local_dir=os.getcwd()+"\\train_label\\"
print(local_dir)
for filename in os.listdir(local_dir):
    newname="mytrain"+str(train[i])+".xml"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

C:\Users\Shaun\CE7454_2018\codes\DeepLearning\train_data\
C:\Users\Shaun\CE7454_2018\codes\DeepLearning\train_label\


Get a vector to record the shuffled position of test set,<br>
and shuffle the data and labels at the same time

In [11]:
# for test sets
test=np.arange(2500)
print(test[0:10])
np.random.shuffle(test)
print(test[0:10])

[0 1 2 3 4 5 6 7 8 9]
[   2    9 1052 1332 1990  832 1844 2109  383  657]


In [12]:
# shuffle the test set
local_dir=os.getcwd()+"\\test_data\\"
print(local_dir)

i=0
for filename in os.listdir(local_dir):
    newname="test"+str(test[i])+".jpg"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

i=0
local_dir=os.getcwd()+"\\test_label\\"
print(local_dir)
for filename in os.listdir(local_dir):
    newname="test"+str(test[i])+".xml"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

C:\Users\Shaun\CE7454_2018\codes\DeepLearning\test_data\
C:\Users\Shaun\CE7454_2018\codes\DeepLearning\test_label\


Exactly the same operation with train set, shuffle the small scale test set

In [13]:
# for small scale test
small=np.arange(900)
print(small[0:10])
np.random.shuffle(small)
print(small[0:10])

[0 1 2 3 4 5 6 7 8 9]
[733 229 211  52 543  71 238 798 647 402]


In [14]:
# shuffle the small scale test set
local_dir=os.getcwd()+"\\small_data\\"
print(local_dir)

i=0
for filename in os.listdir(local_dir):
    newname="small"+str(small[i])+".jpg"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

i=0
local_dir=os.getcwd()+"\\small_label\\"
print(local_dir)
for filename in os.listdir(local_dir):
    newname="small"+str(small[i])+".xml"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

C:\Users\Shaun\CE7454_2018\codes\DeepLearning\small_data\
C:\Users\Shaun\CE7454_2018\codes\DeepLearning\small_label\
