In [1]:
# select u% pictures from each class
# seperate the selected pictures into training set (train_u%) and testing set (test_u%)

import random as rm
import os
from shutil import copyfile, rmtree
import torch

In [2]:
raw_dir ="D:\download\DACcontest\data_training_V4\data_training\\"
train_data_dir = "D:\download\DACcontest\data_training_V4"+"\\train_data\\"
train_label_dir = "D:\download\DACcontest\data_training_V4" + "\\train_label\\"
test_data_dir = "D:\download\DACcontest\data_training_V4" + "\\test_data\\"
test_label_dir = "D:\download\DACcontest\data_training_V4" + "\\test_label\\"
data_dir="D:\download\DACcontest" + "\\data\\"
label_dir="D:\download\DACcontest" + "\\label\\"
print(train_data_dir,train_label_dir)
print(test_data_dir,test_label_dir)
print(data_dir,label_dir)

D:\download\DACcontest\data_training_V4\train_data\ D:\download\DACcontest\data_training_V4\train_label\
D:\download\DACcontest\data_training_V4\test_data\ D:\download\DACcontest\data_training_V4\test_label\
D:\download\DACcontest\data\ D:\download\DACcontest\label\


In [19]:
raw_dir ="D:\download\DACcontest\data_training_V4\data_training\\"
data_dir="D:\download\segment\segment2\\"
label_dir=data_dir
print(data_dir,label_dir)

D:\download\segment\segment2\ D:\download\segment\segment2\


In [24]:
ratio=3
accratio=2*ratio

global_num=0    # for all images

local_num=0 # for images in a floder
local_dir=raw_dir + "riding9"
print(local_dir)
print(global_num)
justnow=0
for filename in os.listdir(local_dir):
    if (local_num%accratio==0):
        copyfile(local_dir +'\\'+ filename, data_dir +"riding"+ filename)
        justnow=1
        global_num+=1
    elif justnow==1 :
        copyfile(local_dir + '\\' +filename, label_dir +"riding"+ filename)
        justnow=0
        global_num+=1
    local_num=local_num+1
        
print(global_num)

D:\download\DACcontest\data_training_V4\data_training\riding9
0
446


In [8]:
# delete origin files in these folders
rmtree(train_data_dir)
os.makedirs(train_data_dir)
rmtree(train_label_dir)
os.makedirs(train_label_dir)
rmtree(test_data_dir)
os.makedirs(test_data_dir)
rmtree(test_label_dir)
os.makedirs(test_label_dir)

In [3]:
raw_list=os.listdir(raw_dir)
print(raw_list[0])
local_dir=raw_dir + raw_list[0] + "/"
print(local_dir)
num=0
for filename in os.listdir(local_dir):
    print(filename)
    num=num+1
    if num==20 :
        break

boat1
D:\download\DACcontest\data_training_V4\data_training\boat1/
000001.jpg
000001.xml
000002.jpg
000002.xml
000003.jpg
000003.xml
000004.jpg
000004.xml
000005.jpg
000005.xml
000006.jpg
000006.xml
000007.jpg
000007.xml
000008.jpg
000008.xml
000009.jpg
000009.xml
000010.jpg
000010.xml


In [13]:
del raw_list
del local_dir
del filename 

In [18]:
ratio=10
accratio=2*ratio

global_num=0    # for all images
for cls in os.listdir(raw_dir):
    local_num=0 # for images in a floder
    local_dir=raw_dir + cls
    print(local_dir)
    print(global_num)
    justnow=0
    for filename in os.listdir(local_dir):
        if (local_num%accratio==0):
            copyfile(local_dir +'\\'+ filename, data_dir + cls + '_' + filename)
            justnow=1
            global_num+=1
        elif justnow==1 :
            copyfile(local_dir + '\\' +filename, label_dir + cls + '_' + filename)
            justnow=0
            global_num+=1
        local_num=local_num+1
        
print(global_num)
        

D:\download\DACcontest\data_training_V4\data_training\boat1
0
D:\download\DACcontest\data_training_V4\data_training\boat2
118
D:\download\DACcontest\data_training_V4\data_training\boat3
218
D:\download\DACcontest\data_training_V4\data_training\boat4
336
D:\download\DACcontest\data_training_V4\data_training\boat5
428
D:\download\DACcontest\data_training_V4\data_training\boat6
696
D:\download\DACcontest\data_training_V4\data_training\boat7
800
D:\download\DACcontest\data_training_V4\data_training\boat8
964
D:\download\DACcontest\data_training_V4\data_training\building1
1050
D:\download\DACcontest\data_training_V4\data_training\building2
1158
D:\download\DACcontest\data_training_V4\data_training\building3
1258
D:\download\DACcontest\data_training_V4\data_training\car1
1322
D:\download\DACcontest\data_training_V4\data_training\car10
1406
D:\download\DACcontest\data_training_V4\data_training\car11
1720
D:\download\DACcontest\data_training_V4\data_training\car12
2144
D:\download\DACcontest\d

In [42]:
global_num=18786
print(global_num/2)
randd=torch.zeros(10,dtype=torch.int8)
print(rand.size())
print(rand.dim(),rand[12])
if rand[10000]==0 :
    print('yes')
print(rand[1000])
rm.seed(datetime.now())
#for i in range(10):
#    print(rm.randint(0,5))

i=0
while i<10 :
    rm_num=rm.randint(0,9)
    if randd[rm_num]==0 :
        randd[rm_num]=1
        i=i+1
    else:
        continue
print(randd)

filename="boat1_000001.jpg"
copyfile(data_dir + filename, raw_dir + filename)

18742.0
torch.Size([18742])
1 tensor(0, dtype=torch.int8)
yes
tensor(0, dtype=torch.int8)
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=torch.int8)


'D:\\download\\DACcontest\\data_training_V4\\data_training\\boat1_000001.jpg'

In [3]:
import time
rm.seed(time.time())
small_num=893
test_num=2500
train_num=6000
total_num=9393
rand=torch.zeros(total_num,dtype=torch.int8)

# set the rand[] for small scale test
i=0
while i<small_num :
    rm_num=rm.randint(0,total_num-1)
    if rand[rm_num]==0 :
        rand[rm_num]=1
        i=i+1
    else :
        continue

# set the rand[] for large scale test/inference
i=0
while i<test_num :
    rm_num=rm.randint(0,total_num-1)
    if rand[rm_num]==0 :
        rand[rm_num]=2
        i=i+1
    else :
        continue

data_dir="D:\download\DACcontest" + "\\data\\"
label_dir="D:\download\DACcontest" + "\\label\\"
train_data_dir = "D:\download\DACcontest\data_training_V4"+"\\train_data\\"
train_label_dir = "D:\download\DACcontest\data_training_V4" + "\\train_label\\"
test_data_dir = "D:\download\DACcontest\data_training_V4" + "\\test_data\\"
test_label_dir = "D:\download\DACcontest\data_training_V4" + "\\test_label\\"
small_data_dir = "D:\download\DACcontest\data_training_V4" + "\\small_data\\"
small_label_dir = "D:\download\DACcontest\data_training_V4" + "\\small_label\\"
print(train_data_dir,train_label_dir)
print(test_data_dir,test_label_dir)
print(small_data_dir,small_label_dir)



D:\download\DACcontest\data_training_V4\train_data\ D:\download\DACcontest\data_training_V4\train_label\
D:\download\DACcontest\data_training_V4\test_data\ D:\download\DACcontest\data_training_V4\test_label\
D:\download\DACcontest\data_training_V4\small_data\ D:\download\DACcontest\data_training_V4\small_label\


In [4]:
print(rand[0:20])

tensor([0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0],
       dtype=torch.int8)


In [5]:
global_num=0    # for all images
for filename in os.listdir(data_dir):
        if (rand[global_num]==1):
            copyfile(data_dir + filename, small_data_dir + filename)
        elif(rand[global_num]==2):
            copyfile(data_dir + filename, test_data_dir + filename)
        else :
            copyfile(data_dir + filename, train_data_dir + filename)
        global_num+=1    
print(global_num)

global_num=0    # for all xmls
for filename in os.listdir(label_dir):
        if (rand[global_num]==1):
            copyfile(label_dir + filename, small_label_dir + filename)
        elif(rand[global_num]==2):
            copyfile(label_dir + filename, test_label_dir + filename)
        else :
            copyfile(label_dir + filename, train_label_dir + filename)
        global_num+=1    
print(global_num)

9393
9393


In [7]:
import numpy as np
train=np.arange(6000)
print(train[0:10])
np.random.shuffle(train)
print(train[0:10])

[0 1 2 3 4 5 6 7 8 9]
[3499 3102 3803 5794 2095 4659 5371 4848 5152 5683]


In [8]:
local_dir=os.getcwd()+"\\train_data\\"
print(local_dir)

i=0
for filename in os.listdir(local_dir):
    newname="mytrain"+str(train[i])+".jpg"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

i=0
local_dir=os.getcwd()+"\\train_label\\"
print(local_dir)
for filename in os.listdir(local_dir):
    newname="mytrain"+str(train[i])+".xml"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

C:\Users\Shaun\CE7454_2018\codes\DeepLearning\train_data\
C:\Users\Shaun\CE7454_2018\codes\DeepLearning\train_label\


In [8]:
print(filename)

boat1_000021.jpg


In [9]:
test=np.arange(2500)
print(test[0:10])
np.random.shuffle(test)
print(test[0:10])

[0 1 2 3 4 5 6 7 8 9]
[  12  664 1909 2197  494 2241 2189 1269 1183 2143]


In [10]:
local_dir=os.getcwd()+"\\test_data\\"
print(local_dir)

i=0
for filename in os.listdir(local_dir):
    newname="test"+str(test[i])+".jpg"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

i=0
local_dir=os.getcwd()+"\\test_label\\"
print(local_dir)
for filename in os.listdir(local_dir):
    newname="test"+str(test[i])+".xml"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

C:\Users\Shaun\CE7454_2018\codes\DeepLearning\test_data\
C:\Users\Shaun\CE7454_2018\codes\DeepLearning\test_label\


In [11]:
small=np.arange(900)
print(small[0:10])
np.random.shuffle(small)
print(small[0:10])

[0 1 2 3 4 5 6 7 8 9]
[599 760 571 244 882 686  36  78 383 177]


In [12]:
local_dir=os.getcwd()+"\\small_data\\"
print(local_dir)

i=0
for filename in os.listdir(local_dir):
    newname="small"+str(small[i])+".jpg"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

i=0
local_dir=os.getcwd()+"\\small_label\\"
print(local_dir)
for filename in os.listdir(local_dir):
    newname="small"+str(small[i])+".xml"
    os.rename(local_dir+filename,local_dir+newname)
    i=i+1

C:\Users\Shaun\CE7454_2018\codes\DeepLearning\small_data\
C:\Users\Shaun\CE7454_2018\codes\DeepLearning\small_label\
